[package]
name = "brimstone"
version = "0.1.0"
authors = ["Robert Sedlacek <rs@474.at>"]

[dependencies]
glib = "*"
gio = "*"
gdk = "*"
pango = "*"
cairo-rs = "*"

[dependencies.webkit2gtk]
version = "*"
features = ["v2_16"]

[dependencies.gtk]
version = "*"
features = ["v3_18"]

